config/routes.rb
Tm::Application.routes.draw do
  get "users/new"

  resources :tasks
  resources :projects
  resources :sessions, only: [:new, :create, :destroy]
  resources :users
  match '/signup', to: 'users#new'
  match '/signin', to: 'sessions#new'
  match '/signout', to: 'sessions#destroy'
  match '/usershow', to: 'users#show'
  match '/tasks/new/:id', to: 'tasks#new'
  match '/tasks/plus/:id', to: 'tasks#plus'
  match '/tasks/minus/:id', to: 'tasks#minus'
  root :to => 'sessions#home'

end

app/models/user.rb
class User < ActiveRecord::Base
  attr_accessible :email, :name, :password, :password_confirmation
  has_secure_password
  validates :password, :presence => {:on => :create}
  validates :name, :presence => true;
  validates :name, :format => { :with => /^([A-z]\s?){3,16}$/i,
      :message => "Only letters and whitespace are allowed in Name" }
  validates :name, :uniqueness=> {:case_sensitive => false, :message => "name is already taken"}
  validates :email, :presence => true;
  validates :email, :format => { :with => /^([A-z0-9\.-_]{2,16})@([A-z0-9\.-_]{2,14})\.([A-z]{2,4})$/i,
                                 :message => "Please, write your real email as email@example.com" }
  validates :email, :uniqueness=> {:case_sensitive => false, :message => "email is already taken"}
  before_save { |user| user.email = email.downcase}
  before_save :create_remember_token
  validates :password_confirmation, :presence => true;
  validates :password, :format => { :with => /^[A-z0-9\!\@\$\%]{6,18}$/i,
      :message => "Only letters, digits and !,@,$,% with length:6-18 symbols are allowed in Password" }
  has_many :projects, dependent: :destroy


  private
    def create_remember_token
      self.remember_token = SecureRandom.urlsafe_base64
    end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  include ProjectsHelper
  include SessionsHelper
  before_filter :signed_in_user, only:[:edit, :update, :destroy]

  # GET /users
  # GET /users.json
  def index
    @users = User.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @users }
    end
  end

  # GET /users/1
  # GET /users/1.json
  def show
    #@user = User.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @user }
    end
  end

  # GET /users/new
  # GET /users/new.json
  def new
    @user = User.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @user }
    end
  end

  # GET /users/1/edit
  def edit
    @user = User.find(params[:id])
  end

  # POST /users
  # POST /users.json
  def create
    @user = User.new(params[:user])

    respond_to do |format|
      if @user.save
        format.html { redirect_to root_path }
        flash.now[:success] = "Welcome to the Task Manager! "
        sign_in @user
        format.json { render json: @user, status: :created, location: @user }
      else
        format.html { render action: "new" }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /users/1
  # PUT /users/1.json
  def update
    @user = User.find(params[:id])

    respond_to do |format|
      if @user.update_attributes(params[:user])
        format.html { redirect_to root_path }
        format.json { head :no_content }
        flash.now[:success] = "User was successfully updated "
      else
        format.html { render action: "edit" }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /users/1
  # DELETE /users/1.json
  def destroy
    @user = User.find(params[:id])
    @user.destroy

    respond_to do |format|
      format.html { redirect_to users_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/_form.html.erb
<%=  provide(:title, 'Sign Up') %>
<%= form_for(@user) do |f| %>
 <%= render 'shared/error_messages', object: f.object %>
<center>
    <div class = "row">
         <div class="span6 offset3">
            <%= f.label :name %><br />
            <%= f.text_field :name %>

            <%= f.label :email %><br />
            <%= f.email_field :email %>

            <%= f.label :password %><br />
            <%= f.password_field :password %>

            <%= f.label :password_confirmation, "Confirmation" %>
            <%= f.password_field :password_confirmation %>
           <br />
            <%= f.submit "Create my account", class: "btn btn-large btn-primary" %>
         </div>
    </div>
</center>
<% end %>

app/views/users/_projects.html.erb
<% count_tasks = 0
   count_tasks_future = 0 %>
<% current_user.projects.each do |project| %>
    <div class="well">
    <table class="table table-stripped">
      <thead>
      <tr>
        <td><b class="icon-list"></b></td>
        <td><b><%= project.name%></b>. Tasks: <%= project.tasks.length%> </td>
        <td></td><td></td>
        <td><div class="input-append"><%= link_to edit_project_path(project), class: "btn btn-primary", method: :get do%><i class="icon-white icon-pencil"></i> <% end %><%= link_to project, confirm: 'Are you sure?', class: "btn btn-primary", method: :delete do %>
              <i class="icon-white icon-trash"></i> <% end %>
              </div></td>
      </tr>
      <tr>
        <td> <b>Done?</b></td>
        <td> <b>Task</b></td>
        <td> <b>End Time</b></td>
        <td> <b>Priority</b></td>
        <td> <b>Activities</b></td>
      </tr>
      </thead>
     <tbody>
      <% project.tasks.each do |task| %>
          <% if task.status == false && task.end_time == Date.today()
                count_tasks +=1 end %>
         <% if task.status == false && task.end_time != Date.today()
              count_tasks_future +=1 end %>
          <tr>
            <%= form_for(task, :remote => true) do |f| %>
            <td><%= f.check_box :status, :onchange => 'this.form.submit()' %></td>
            <% end %>
            <td><%= task.name%></td>
            <td><%= task.end_time %></td>
            <td><%= link_to "/tasks/minus/"+task.id.to_s do %>
                  <i class="icon-minus"></i>  <% end %>
              <%= task.priority.to_s %>
              <%= link_to  "/tasks/plus/"+task.id.to_s do %>
                  <i class="icon-plus"></i>  <% end %>
            </td>
            <td>
              <div class="input-append"><%= link_to edit_task_path(task), class: "btn btn-primary", method: :get do%><i class="icon-white icon-pencil"></i> <% end %><%= link_to task, confirm: 'Are you sure?', class: "btn btn-primary", method: :delete do %>
                    <i class="icon-white icon-trash"></i> <% end %>
              </div>
            </td>
          </tr>
      <% end %>
     </tbody>
    </table>
      <form accept-charset="UTF-8" action="" class="well form-inline" id="new_task" method="post">
        <center><%= link_to "Create task", new_task_path+"/"+project.id.to_s, :class => "btn btn-success"%></center>
      </form>
    </div>
<% end %>

<center>
<%= button_to 'Add TODO List', new_project_path, :class => "btn btn-large btn-primary", :form => {"data-type"=> "json"}, :method => "get" %>
</center>
<% if count_tasks > 0
     provide(:todo, " You have to do "+ count_tasks.to_s + " task(s) for today and "+ count_tasks_future.to_s+" more in future.") end %>

app/views/users/edit.html.erb
<%=  provide(:title, 'Profile edit') %>
<%= form_for(@user) do |f| %>
    <%= render 'shared/error_messages', object: f.object %>
    <center>
      <div class = "row">
        <div class="span6 offset3">
          <%= f.label :name %><br />
          <%= f.text_field :name %>

          <%= f.label :email %><br />
          <%= f.email_field :email %>

          <%= f.label :password %><br />
          <%= f.password_field :password %>

          <%= f.label :password_confirmation, "Confirmation" %>
          <%= f.password_field :password_confirmation %>
          <br />
          <%= f.submit "Save", class: "btn btn-large btn-primary" %>
        </div>
      </div>
    </center>
<% end %>

<%= link_to 'Back', root_path %>

app/views/users/index.html.erb
<h1>Listing users</h1>

<table>
  <tr>
    <th>Name</th>
    <th>Email</th>
    <th>Password</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @users.each do |user| %>
  <tr>
    <td><%= user.name %></td>
    <td><%= user.email %></td>
    <td><%= user.password %></td>
    <td><%= link_to 'Show', user %></td>
    <td><%= link_to 'Edit', edit_user_path(user) %></td>
    <td><%= link_to 'Destroy', user, confirm: 'Are you sure?', method: :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New User', new_user_path %>

app/views/users/new.html.erb
<%= render 'form' %>

<%= link_to 'Back', root_path %>

app/views/users/show.html.erb
<p id="notice"><%= notice %></p>
<% provide(:title, "Hi, " + current_user.name + "! ") %>
<p>

  <b>Name:</b>
  <%= current_user.name %> | <%= link_to 'Edit Profile', edit_user_path(current_user) %>
</p>

<p>
  <%= render 'projects' %>
</p>