config/routes.rb
Tm::Application.routes.draw do
  get "users/new"

  resources :tasks
  resources :projects
  resources :sessions, only: [:new, :create, :destroy]
  resources :users
  match '/signup', to: 'users#new'
  match '/signin', to: 'sessions#new'
  match '/signout', to: 'sessions#destroy'
  match '/usershow', to: 'users#show'
  match '/tasks/new/:id', to: 'tasks#new'
  match '/tasks/plus/:id', to: 'tasks#plus'
  match '/tasks/minus/:id', to: 'tasks#minus'
  root :to => 'sessions#home'

end

app/models/project.rb
class Project < ActiveRecord::Base
  attr_accessible :name, :user_id
  belongs_to :user
  has_many :tasks, dependent: :destroy
  validates :user_id, presence: true
  validates :name, presence: true, length: {maximum: 100}
end

app/controllers/projects_controller.rb
class ProjectsController < ApplicationController
  before_filter :signed_in_user, only: [:create, :destroy]
  # GET /projects
  # GET /projects.json
  include SessionsHelper
  include ProjectsHelper
  def index
    @projects = Project.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @projects }
    end
  end

  # GET /projects/1
  # GET /projects/1.json
  def show
    @project = Project.find(params[:id])
    @tasks = @project.tasks.paginate(page: params[:page])
    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @project }
    end
  end

  # GET /projects/new
  # GET /projects/new.json
  def new
    @project = Project.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @project }
    end
  end

  # GET /projects/1/edit
  def edit
    @project = Project.find(params[:id])
  end

  # POST /projects
  # POST /projects.json
  def create
    @project = current_user.projects.build(params[:project])
    @project.user_id = current_user.id
    respond_to do |format|
      if @project.save
        format.html { redirect_to root_path}
        flash.now[:success] = 'Project was successfully created.'
        format.json { render json: @project, status: :created, location: @project }
      else
        format.html { render action: "new" }
        format.json { render json: @project.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /projects/1
  # PUT /projects/1.json
  def update
    @project = Project.find(params[:id])

    respond_to do |format|
      if @project.update_attributes(params[:project])
        format.html { redirect_to root_path, notice: 'Project was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @project.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /projects/1
  # DELETE /projects/1.json
  def destroy
    @project = Project.find(params[:id])
    @project.destroy

    respond_to do |format|
      format.html { redirect_to root_path }
      format.json { head :no_content }
    end
  end
end

app/helpers/projects_helper.rb
module ProjectsHelper

  def current_project= project
      @current_project = project
  end

  def current_project
    @current_project
  end
end

app/views/projects/_form.html.erb
<%=  provide(:title, 'New TODO List') %>
<%= form_for(@project) do |f| %>
   <%= render 'shared/error_messages', object: f.object %>

    <center>
      <div class = "row">
        <div class="span6 offset3">
          <%= f.label :name %><br />
          <%= f.text_field :name %>
          <%= button_to 'Create TODO List', new_project_path, :class => "btn btn-large btn-primary", :form => {"data-type"=> "json"}, :method => "post" %>

        </div>
      </div>
    </center>

<% end %>

app/views/projects/edit.html.erb
%=  provide(:title, 'New TODO List') %>
<%= form_for(@project) do |f| %>
    <%= render 'shared/error_messages', object: f.object %>

    <center>
      <div class = "row">
        <div class="span6 offset3">
          <%= f.label :name %><br />
          <%= f.text_field :name %>
          <%= button_to 'Edit', new_project_path, :class => "btn btn-large btn-primary", :form => {"data-type"=> "json"}, :method => "put  " %>

        </div>
      </div>
    </center>
<% end %>
<%= link_to 'Back', root_path %>

app/views/projects/index.html.erb
<h1>Listing projects</h1>

<table>
  <tr>
    <th>Name</th>
    <th>User</th>
    <th></th>
    <th></th>
  </tr>

<% @projects.each do |project| %>
  <tr>
    <td><%= project.name %></td>
    <td><%= project.user_id %></td>
    <td><%= link_to 'Show', project %></td>
    <td><%= link_to 'Edit', edit_project_path(project) %></td>
    <td><%= link_to 'Destroy', project, confirm: 'Are you sure?', method: :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Project', new_project_path %>

app/views/projects/new.html.erb
<h1>New project</h1>

<%= render 'form' %>

<%= link_to 'Back', root_path %>

app/views/projects/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Name:</b>
  <%= @project.name %>
</p>

<p>
  <b>User:</b>
  <%= @project.user_id %>
</p>

<p>
  <b>Tasks:</b>
  <%= @project.tasks %>
</p>

<%= link_to 'Edit', edit_project_path(@project) %> |
<%= link_to 'Back', projects_path %>