config/routes.rb
Tm::Application.routes.draw do
  get "users/new"

  resources :tasks
  resources :projects
  resources :sessions, only: [:new, :create, :destroy]
  resources :users
  match '/signup', to: 'users#new'
  match '/signin', to: 'sessions#new'
  match '/signout', to: 'sessions#destroy'
  match '/usershow', to: 'users#show'
  match '/tasks/new/:id', to: 'tasks#new'
  match '/tasks/plus/:id', to: 'tasks#plus'
  match '/tasks/minus/:id', to: 'tasks#minus'
  root :to => 'sessions#home'

end

app/views/layouts/_footer.html.erb
<footer class="footer">
  <small>
    <a href="http://vk.com/suchav">Task Manager</a>
    by Artem
  </small>
  <nav>
    <ul>
      <li><%= link_to "About",   '#' %></li>
      <li><%= link_to "Contact", '#' %></li>
    </ul>
  </nav>
</footer>

app/views/layouts/_header.html.erb
<header class="navbar navbar-fixed-top">
  <div class="navbar-inner">

    <div class = "container">
     
     
     
     <a id="logo" href ="<%= root_path %>"><%=  yield(:title) %>  <%= yield(:todo) %></a>
      <nav>
        <ul class="nav pull-right">
          <% if signed_in? %>
          <li><%= link_to "Sign Out", signout_path, method: "delete" %></li>
          <% end %>
        </ul>
      </nav>
    </div>
  </div>
</header>

app/views/layouts/_shim.html.erb
<!--[if lt IE 9]>
<script src="http://html5shim.googlecode.com/svn/trunk/html5.js"></script>
<![endif]-->

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title><%= full_title(yield(:title)) %></title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
  <%= render 'layouts/shim' %>

</head>
<body>

    <%= render 'layouts/header' %>
    <div class="container">
      <% flash.each do |key, value| %>
          <div class = "alert alert-<%= key %>"><%= value %></div>
       <% end %>
      <div class="center">
        <h1>TODO LISTS</h1>
        <h2>Task Manager</h2>
      </div>
      <%= yield %>
      <%= render 'layouts/footer' %>
    <!--  <%= debug(params) if Rails.env.development? %>   -->
    </div>
</body>
</html>